### ISSUE TITLE
Dados do partido incorretos na votação

### ISSUE THREAD

**Issue by paul0vinicius** [labhackercd/dados-abertos#100]
Oi, pessoal. Percebi o seguinte _bug_:

Ao recuperar os dados da API, ela retorna os dados do partido atual de um parlamentar e não o do partido cuja data da votação fora realizada.

Por exemplo, nos votos da PEC171 da votação ocorrida no dia 30/06/2015, a deputada Luiza Erundina era filiada ao partido PSB. Porém, ao fazer uma consulta dos votos utilizando a API ele retorna que a candidata era filiada ao PSOL. Eu acho que por baixo dos panos, a API faz uma consulta direta usando a função para pegar os detalhes de um deputado e joga partido atual como se fosse o da época em que a votação ocorreu.

Sabendo que _6429_ é o ID da referida votação acima e fazendo: `curl -X GET "https://dadosabertos.camara.leg.br/api/v2/votacoes/6429/votos?pagina=3&itens=513" -H  "accept: application/json"`, temos como resposta:

```
{
      "voto": "Não",
      "parlamentar": {
        "id": 74784,
        "uri": "https://dadosabertos.camara.leg.br/api/v2/deputados/74784",
        "nome": "LUIZA ERUNDINA",
        "siglaPartido": "PSOL",
        "uriPartido": "https://dadosabertos.camara.leg.br/api/v2/partidos/36839",
        "siglaUf": "SP",
        "idLegislatura": 55,
        "urlFoto": "http://www.camara.leg.br/internet/deputado/bandep/74784.jpg"
      }
    }
```

 que difere de 
```
<Deputado Nome="Luiza Erundina" ideCadastro="74784" Partido="PSB " UF="SP" Voto="Não "/>
``` 
resultado retornado em uma consulta à mesma votação utilizando a API antiga.

Atenciosamente,

**Comment by CeninCD** [comment]
Olá, Paulo!

Obrigado pela mensagem e desculpe pela demora na verificação -- que confirmou o problema. na verdade, foram feitos alguns testes usando o identificador de votação que você havia passado anteriormente, o que causou uma certa confusão. Mas acabei de testar de novo com o identificador 6429 e vi que você está certo.

Continuamos tendo problemas enormes com os dados de votações, ainda mal obtidos da base de registro de votações do Plenário. A correta identificação do partido do parlamentar no momento da votação, como você apontou, é um desses problemas. Vamos tentar resolver o mais rapidamente possível.

Obrigado mais uma vez, desculpe e um abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by CeninCD** [comment]
Olá, Paulo!

Tentamos corrigir o problema na atualização 0.2.5, de 27/09. Você poderia conferir, por favor?

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by paul0vinicius** [comment]
Olá, Fabricio.

Acabei de conferir aqui com alguns testes e o problema parece ter sido resolvido.

Muito obrigado e abraços (:

Atenciosamente,
