### ISSUE TITLE
ID do partido indisponivel

### ISSUE THREAD

**Issue by kurtye** [labhackercd/dados-abertos#108]
Seguindo o exemplo
https://dadosabertos.camara.leg.br/api/v2/partidos/{id}

https://dadosabertos.camara.leg.br/api/v2/partidos/36769
 não retorna nenhum dado do partido através do ID

**Comment by kurtye** [comment]
<erroCorpo>
<status>404</status>
<title>Requisição inválida</title>
<detail>
A URL passada se refere a um recurso que não existe no sistema.
</detail>
<instance>
https://dadosabertos.camara.leg.br/api/v2/partidos/36769
</instance>
<code/>
</erroCorpo>

**Comment by CeninCD** [comment]
Olá, kurtye!

Não estou achando agora, mas tenho quase certeza de que já temos um relato desse problema. Houve recentemente alterações na base de dados com informações sobre os partidos, e isso quebrou o nosso serviço. Nesta quarta vamos colocar no ar um novo _build_ que deverá corrigir esse problema (entre outros).

Desculpe, obrigado pelo aviso e um abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by ptcampos** [comment]
Olá! Estou acompanhando a solução... Aqui retorna o mesmo erro.. 404 (não encontrado).
