### ISSUE TITLE
Pareceres de uma proposição

### ISSUE THREAD

**Issue by gleidsonp** [labhackercd/dados-abertos#11]
Alguém pode me mostrar onde posso obter via serviços os pareceres de uma proposição?

Obrigado.

**Comment by RodolfoViana** [comment]
É possível encontrar a situação atual de uma proposição pelo o comando http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/proposicoes-1/listarsituacoesproposicao
