### ISSUE TITLE
Erro 404 na chamada ao método GET /deputados/{id}

### ISSUE THREAD

**Issue by paul0vinicius** [labhackercd/dados-abertos#111]
Olá mais uma vez, pessoal.
Percebi um bug estranho hoje pela manhã.
Ao fazer:
```
curl -X GET "https://dadosabertos.camara.leg.br/api/v2/deputados/178957" -H  "accept: application/json"
```
que deveria retornar os dados do deputado Abel Salvador Mesquita Júnior, retorna agora erro 404.

Apesar do erro, ainda consigo acessar os dados do deputado dessa forma:
```
https://dadosabertos.camara.leg.br/api/v2/deputados?id=178957
```

Embora essa solução funcione, alguns campos estão faltando, tais quais: sexo, data de nascimento, uf de nascimento, municipio de nascimento, cpf e escolaridade - disponíveis anteriormente. Além disso, um objeto chamado _ultimoStatus_ contendo informações mais recentes sobre a atuação do deputado também está faltando ao fazer a chamada por esse método.

**Comment by CeninCD** [comment]
Olá, Paulo!

Descobrimos esse problema por aqui também. Estamos tentando descobrir o que houve, e aparentemente foi uma alteração feita no banco de dados (para ser mais específico: nossa query acessa uma view que passou a acessar uma outra view de um banco para o qual nosso usuário não tinha acesso).

Só consegui identificar o problema no endpoint _/deputados/{id}_. Se você encontrar outros com esse problema, por favor avise de novo!

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by CeninCD** [comment]
Olá de novo!

Aparentemente o problema foi resolvido!

Desculpe e obrigado de novo!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by paul0vinicius** [comment]
Sim, o problema já fora resolvido. Muito obrigado!

Atenciosamente,
