### ISSUE TITLE
Descontinuação dos Webservices antigos.

### ISSUE THREAD

**Issue by DaniloOliveira28** [labhackercd/dados-abertos#112]
Olá time dos Dados Abertos da Câmara,

Existe alguma previsão de descontinuamento do antigo serviço (link abaixo) de dados abertos da Câmara?

http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo

Obrigado!

**Comment by CeninCD** [comment]
Olá, Danilo!

Não há previsão de descontinuamento, embora nesses _webservices_ só façamos atualmente _bugfixes_. Estamos resolvendo problemas e acrescentando funcionalidades inéditas na nova API para que os usuários antigos migrem para ela voluntariamente. Mesmo assim, os _webservices_ em SOAP continuam em operação por tempo indeterminado.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
