### ISSUE TITLE
Problemas na busca por despesas

### ISSUE THREAD

**Issue by vitallan** [labhackercd/dados-abertos#131]
Não sei se esse é o caminho certo para informar bugs ou duvidas. Se estiver errado, por favor me avisem.

Não estou conseguindo efetuar busca de despesas por deputado. Não dá erro ou algo do genero, apenas retorna vazio. Testando inclusive pelo swagger da pagina de dados abertos, retorna vazio (testei com o id do deputado Abel Mesquita Jr.)

Evidencia:
![evidencia](https://user-images.githubusercontent.com/1127201/33316227-5f8efc2e-d41a-11e7-9f15-1003adff51ce.png)

**Comment by CeninCD** [comment]
Olá, Vitallan!

Aparentemente aconteceu alguma mudança ou algum problema de acesso na base de dados com as informações de despesas. Vamos olhar aqui, deve ser algo rápido de resolver.

E sim, aqui é o lugar pra essas dúvidas e informações mesmo!

Obrigado pelo aviso e grande abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by CeninCD** [comment]
Olá de novo!

O problema não é tão simples quanto imaginávamos, mas não é da API. Ainda pela manhã foi detectado um problema de carga na base de dados, que é feita pela madrugada. Pedimos que fosse feita uma nova tentativa e verificação de carga, que está em execução neste momento e pode levar cerca de 1h. É possível que o _endpoint_ volte ao normal até umas 17h.

Desculpe, pessoal. Obrigado pela compreensão!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by vitallan** [comment]
Oi Fabricio, tudo bem?

Obrigado pela atenção e agilidade na resposta. 

O endpoint continua respondendo uma lista vazia. Seria possível verificar a carga novamente?

abraço!
Allan Vital

**Comment by CeninCD** [comment]
Obrigado, Allan! Estamos tentando descobrir o que foi que deu errado dessa vez..... Desculpe novamente!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by CeninCD** [comment]
Olá, Allan!

A base foi finalmente carregada e o serviço voltou a funcionar normalmente. Por favor avise se encontrar problemas novamente!

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by vitallan** [comment]
Tudo funcionando agora!

obrigado!

**Comment by leoqbc** [comment]
Boa tarde, o mesmo problema está acontecendo comigo, talvez pela quantidade de requests o endpoint simplesmente passa a responder dados como array vazia.

Será carga? como não existe agrupamento e nem filtros mais detalhados neste endpoint, minha aplicação precisa enviar 12 requests seguidos para trazer os 12 meses gastos do deputado escolhido, quando fiz a implementação estava tudo funcionando porém quando comecei a explorar com outros deputados tive esse problema(até agora não vem nenhuma informações mais em despesas).

Simplesmente a api parou de retornar "dados", uma sugestão interessante seria colocar um header de retorno como ex: Cache-Control: max-age=6000, para que assim requests já devolvidos sejam cacheados, evitam sobrecarga no servidor.

Aguardo um retorno, agradeço desde já.

**Comment by CeninCD** [comment]
Olá, pessoal.

Desculpem a demora na resposta. Nós descobrimos que desde 21/12 há, de fato, um problema de carga de dados na base que é usada pelo Dados Abertos, tanto para a API quanto para a geração dos arquivos com os dados das despesas pela Cota para Exercício da Atividade Parlamentar.

Estamos buscando uma solução junto à área responsável pelos dados.

Mais uma vez desculpem e obrigado pelos alertas.

Fabricio Rocha
Equipe Dados Abertos - Câmara
