### ISSUE TITLE
Comissões externas

### ISSUE THREAD

**Issue by rapcal** [labhackercd/dados-abertos#135]
Boa tarde.
Não estão sendo listadas as comissões externas no [endpoint de Orgãos](http://www.camara.leg.br/SitCamaraWS/Orgaos.asmx/ObterOrgaos) da versão original dos dados abertos.
Alguma previsão de fix?
Muito obrigado!

**Comment by CeninCD** [comment]
Olá, Raphael!

Infelizmente a resposta é negativa. Desde a publicação da nova API, passamos a fazer com os _webservices_ da verão anterior do Dados Abertos apenas correções de bugs. Não retornar as comissões externas (e alguns outros tipos de órgãos) foi uma questão de escolha do projeto desses _webservices_ na época.

Na nova API, você pode obter uma lista de todas as comissões externas pela URL `https://dadosabertos.camara.leg.br/api/v2/orgaos?idTipoOrgao=5` .

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by rapcal** [comment]
Perfeito, Fabricio.
Então vocês já recomendam o uso da nova API em produção? Como está em alpha, entendíamos que ainda não era o caso.
Obrigado!

**Comment by CeninCD** [comment]
Olha, uma coisa não tem lá muito a ver com a outra, veja bem... A versão anterior do Dados Abertos é "estável" porque já há um bom tempo (bem antes da nova API) não sofre alterações significativas em endpoints, em conjuntos de dados fornecidos, em identificadores, em parâmetros e valores que se possa atribuir a eles, etc.

A nova API tem o objetivo de ser muito mais abrangente, mas permanece considerada _alpha_ e "instável" porque ainda falta implementar vários dos _endpoints_ previstos em sua especificação, alguns identificadores ainda precisam de definições das áreas fornecedoras dos dados (especialmente os de votações), e nesse processo vão aparecendo _bugs_ que podem ser problemáticos para sistemas "de produção".

Essa parte de órgãos, em particular, passou recentemente a fornecer dados sobre as comissões externas e, mais recentemente ainda, sobre as subcomissões. Mas a parte de identificadores, por exemplo, já está razoavelmente definida. Dependendo da sua aplicação, pode ser que ela já seja suficientemente estável, mas de qualquer forma eu recomendaria que você fizesse alguns testes por um certo período antes de aplicá-lo diretamente em produção. E o que você encontrar de problemas nesse período, por favor avise!!

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by rapcal** [comment]
Entendido! Em resumo a Câmara dos Deputados não fornece, atualmente, dados abertos sobre Comissões Externas para utilização em ambiente de produção.
Obrigado mais uma vez pela informação e suporte, Fabrício!
