### ISSUE TITLE
Prazo para migração para nova versão da API

### ISSUE THREAD

**Issue by pauloabelha** [labhackercd/dados-abertos#144]
Olá,

Primeiramente parabéns pelo incrível esforço de modernizar a democracia do nosso país! 
Gostaria de saber se há algum prazo para migração total para a nova versão da API.
Pergunto isso pois estou em dúvida se continuo desenvolvendo para a versão antiga ou para a nova já que alguns campos e requisicões parecem ter mudado.

Obrigado e abraços,
Paulo

**Comment by CeninCD** [comment]
Salve, Paulo!

Obrigado pelas palavras!

Olha, não há até o momento uma data definida para que a API anterior saia do ar, especialmente porque a nova versão ainda está em _alpha_ (e o desenvolvimento está parado desde o fim de 2017, por problemas de pessoal). Algumas informações, como os discursos dos parlamentares em Plenário, ainda não foram implementados na nova API, e isso talvez demore um bocado ainda.

De toda forma, a versão anterior não vai mais ter evoluções, e nós queremos que os desenvolvedores comecem a usar o quanto antes a nova API, porque isso tem nos dado um precioso feedback sobre erros e melhorias. Todo o nosso esforço de evolução está direcionado para essa versão e para os novos arquivos para download, e a tendência é que em algum tempo suas funcionalidades e vantagens superem com folga os _webservices_ antigos. Esperamos que em algum momento seja possível desativar a API anterior por simples falta de uso, em decorrência de seus usuários terem migrado para a nova versão.

Obrigado mais uma vez e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by pauloabelha** [comment]
Obrigado, Fabricio!

Mão na massa então! Vou começar a migrar meu código.

Abraços,
