### ISSUE TITLE
Erro 403

### ISSUE THREAD

**Issue by AlessandraFernandes** [labhackercd/dados-abertos#145]
Bom dia!
Desde o início da semana identificamos muita instabilidade no acesso aos acessos aos serviços da CD, com erro "403: Acesso negado". Gostaria de entender se este cenário é devido a alguma alteração ou descontinuidade dos serviços?
Atualmente fazemos o acesso de diversos serviços por meio da  "Versão original do Dados Abertos. "http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo", mas verificamos que já existem novos serviços em tecnologia RESTFull. 
Há previsão para desativação dos serviços na versão original?
![erro cd](https://user-images.githubusercontent.com/37146277/37094013-3031a336-21f0-11e8-9027-27b395d51eae.png)

**Comment by CeninCD** [comment]
Olá, Alessandra!

Estes mesmos assuntos estão tratados nos posts #143 e #144 . Vou fechar aqui para continuar por lá, tudo bem?

Obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by AlessandraFernandes** [comment]
Prezados Fabricio, boa tarde.

Todas as dúvidas foram esclarecidas.
Agradeço a atenção e desejo uma excelente semana.

Att.
Alessandra.
