### ISSUE TITLE
O autor da proposição é diferente na nova API

### ISSUE THREAD

**Issue by henriquecoutobsb** [labhackercd/dados-abertos#154]
Na [versão original dos dados abertos](http://www.camara.leg.br/SitCamaraWS/Proposicoes.asmx/ObterProposicao?tipo=PLN&numero=3&ano=2015) temos no PLN 3/2015:
```
<Autor>Presidência da República</Autor>
```
Ao consultar na [nova API](https://dadosabertos.camara.leg.br/api/v2/proposicoes/1230335), o que temos é:
```
    "tipoAutor": "Órgão do Poder Executivo",
    "idTipoAutor": 30000,
    "uriAutores": null,
```
Como devemos proceder para recuperar o autor na nova API quando este não for um deputado?

**Comment by CeninCD** [comment]
Olá, Henrique!

Optamos por incluir na representação de uma proposição apenas as URIs para obtenção de informações dos autores, que na maiorias dos casos são deputados, para não criar mais estruturas aninhadas no retorno. Não temos ainda nas bases de dados da Câmara URLs que identifiquem unicamente os órgãos diversos do Poder Executivo. Incluir apenas os nomes poderia funcionar bem para esses órgãos, mas seria muito insuficiente para identificar os parlamentares.

De toda forma vou incluir essa questão na nossa lista de possíveis melhorias.

Abraço e obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by henriquecoutobsb** [comment]
Prezado Fabrício,

No caso dos deputados a solução funciona adequadamente com a URI e já estamos utilizando. No entanto o nome do órgão do Poder Executivo é fundamental quando não se trata de um deputado.
Vamos aguardar as melhorias e temos esperança de que isto seja implementado.

Há alguma previsão de retomada do desenvolvimento?

**Comment by CeninCD** [comment]
Um novo programador entrou na equipe na semana passada. Já fez algumas correções de bugs e está tentando resolver alguns dos imensos e fundamentais pepinos que temos -- por exemplo, dados históricos dos deputados e unificação dos dados de votações. Não tá nada fácil, mas vamos acreditar no velho _piano piano si va lontano_...

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by CeninCD** [comment]
Olá, Henrique!

Não sei se você já deu uma olhada na atualização da API que fizemos no fim da semana passada. O novo _endpoint_ `/proposicoes/{id}/autores` está fornecendo o nome do órgão como você pediu. Avalie lá!

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by henriquecoutobsb** [comment]
Prezado Fabrício, já atualizamos a aplicação para utilizar a nova estrutura de autor. Funciona perfeitamente. Obrigado.
