### ISSUE TITLE
Arquivo de despesas possui valores negativos no vlrDocumento

### ISSUE THREAD

**Issue by joseildofilho** [labhackercd/dados-abertos#161]
No [CSV](https://dadosabertos.camara.leg.br/swagger/api.html) das despesas, que é fornecido na api, ele possui um campo 'vlrDocumento', este campo possui em sua maioria valores acima de 0, indicando o valor que foi gasto, mas tambem possui valores negativos. Nota-se tambem que é uma quantidade alta desses valores e que não foram são apenas em um ano.
Logo a duvida é oque eles estão representando, erro, ou apenas que os valores das despesas com sinais negativos ?
![menor_que_0](https://user-images.githubusercontent.com/8854932/39264831-2e311ec2-489c-11e8-83d5-f2f8503bfd58.jpg)

**Comment by CeninCD** [comment]
Salve, Joseildo!

Os valores negativos para _vlrLiquido_ e _vlrDocumento_ geram uma dúvida comum sobre os arquivos de Despesas. Recebi uma por e-mail em março sobre isso, e obtive a seguinte explicação do pessoal responsável pelo sistema e pela base de dados da cota para exercício da atividade parlamentar:

>Quando se tratar de bilhete aéreo, esse valor poderá ser negativo, significando que o referido bilhete é um bilhete de compensação, pois compensa um outro bilhete emitido e não utilizado pelo deputado (idem para o dado vlrLiquido).

Espero que isso responda sua questão. Os arquivos de despesas dos deputados ainda têm uma estrutura antiga que basicamente é uma reprodução de uma tabela da base de dados. Não alteramos quando fizemos a divisão dos arquivos por ano, mas ainda vamos planejar uma nova versão que seja mais clara em relação a este e outros pontos.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
