### ISSUE TITLE
 /votacoes/{id}/votos não retorna nada

### ISSUE THREAD

**Issue by marimeireles** [labhackercd/dados-abertos#169]
O meu código:
```
import requests
import json

dados = []

r = requests.get('https://dadosabertos.camara.leg.br/api/v2/proposicoes/2120097/votacoes')
dadosAbertos = r.json()

with open('test.json', 'a') as out:
  out.write(json.dumps(dadosAbertos))
```
O que retorna é:
```
{"dados": [], "links": [{"href": "https://dadosabertos.camara.leg.br/api/v2/proposicoes/2120097/votacoes", "rel": "self"}]}
```

O site dá status 200 como se tivesse tudo certo, mas, nada em /votacoes/ retorna alguma coisa.

Alguma ideia do que é o problema?
Obrigada!

**Comment by CeninCD** [comment]
Olá, Mari!

Todos os _endpoints_ de votação que estão no ar na API não estão funcionando ou confiáveis. Continuamos tendo um sério problema de acesso e organização das bases de dados de votações e não temos da área responsável qualquer previsão de quando (e _se_) esses problemas serão solucionados.

Obrigado pelo contato e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by marimeireles** [comment]
Entendi.

Vou fechar o PR então.

Muito obrigada pela resposta Fabrício.

Abraços.
