### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by paulohubert** [labhackercd/dados-abertos#17]
Olá.

Sou pesquisador do NECI-USP, e estou desenvolvendo uma aplicação em C++ com uma interface de acesso aos WebServices da câmara.
Notei que desde sábado último, 15/08, os serviços estão desativados. Há alguma previsão para o retorno?

**Comment by gbrego** [comment]
Você poderia dizer em qual web-service que você encontrou "Service Unavailable"?

**Comment by diraol** [comment]
Olhando o log do build do Radar Parlamentar dá pra ver que, no mínimo,  os métodos que retornam os conteúdos abaixo estiveram/estão com problemas:
listar_proposicoes
obter_proposicao_por_id
obter_votacoes
(esses métodos são do próprio radar parlamentar, mas consultam endpoints homônimos)
https://travis-ci.org/radar-parlamentar/radar

**Comment by paulohubert** [comment]
Minha aplicação utiliza atualmente todos os webservices, exceto os
referentes a SessoesReunioes.
Até onde posso dizer, nenhum dos serviços estavam funcionando.

On Mon, Aug 17, 2015 at 10:04 AM, Diego Rabatone Oliveira <
notifications@github.com> wrote:

> Olhando o log do build do Radar Parlamentar dá pra ver que, no mínimo, os
> métodos que retornam os conteúdos abaixo estiveram/estão com problemas:
> listar_proposicoes
> obter_proposicao_por_id
> obter_votacoes
> (esses métodos são do próprio radar parlamentar, mas consultam endpoints
> homônimos)
> https://travis-ci.org/radar-parlamentar/radar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/labhackercd/dados-abertos/issues/17#issuecomment-131811169>
> .
>



-- 
Paulo Hubert

**Comment by paulohubert** [comment]
Caros,

os web services voltaram a funcionar, mas agora estou recebendo uma mensagem de erro ao acessar a ficha de tramitação da proposição.
A URL que estou acessando é

http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao=460160

E a mensagem é

Entre em contato com a Central de Atendimento pelo e-mail ceace.cenin@camara.gov.br ou pelo telefone (61) 3216-3636 e informe o seguinte código: 1808.1116.19

Vocês sabem o que está havendo?

**Comment by labhacker** [comment]
Prezados, estou encerrando o ticket pois acredito que o problema tenha sido resolvido. Caso volte a ocorrer, por favor respondam neste ticket para que possamos tomar as providências.

Grato,

Pedro Brandão
Laboratório Hacker
