### ISSUE TITLE
Arquivos XMLs codificados com UTF-16

### ISSUE THREAD

**Issue by marcelometal** [labhackercd/dados-abertos#175]
Olá, gostaria de entender porque não usar `UTF-8` como `encoding` dos XMLs, uma vez que seria bem melhor baixar arquivos menores ([AnoAnterior.zip](http://www.camara.gov.br/cotas/AnoAnterior.zip), [AnoAtual.zip](http://www.camara.gov.br/cotas/AnoAtual.zip) e [AnosAnteriores.zip](http://www.camara.gov.br/cotas/AnosAnteriores.zip)).

$ file -i *.xml
```
AnoAnterior.xml:    text/xml; charset=utf-16le
AnoAtual.xml:       text/xml; charset=utf-16le
AnosAnteriores.xml: text/xml; charset=utf-16be
```

$ du -h *.xml
```
617M	AnoAnterior.xml
273M	AnoAtual.xml
6.5G	AnosAnteriores.xml
```

Convertendo para utf-8 cai pela metade praticamente o tamanho dos arquivos

```
iconv -f UTF-16LE -t UTF-8 AnoAnterior.xml -o AnoAnterior.utf8.xml
iconv -f UTF-16LE -t UTF-8 AnoAtual.xml -o AnoAtual.utf8.xml
iconv -f UTF-16be -t UTF-8 AnosAnteriores.xml -o AnosAnteriores.utf8.xml
```

$ du -h *.utf8.xml

```
310M	AnoAnterior.utf8.xml
137M	AnoAtual.utf8.xml
3.3G	AnosAnteriores.utf8.xml
```

**Comment by CeninCD** [comment]
Salve, Marcelo!

Obrigado pelo contato e pelo interesse no **Dados Abertos**!

Posso te dizer que seu desejo já foi atendido! Dê uma olhada na página de arquivos do portal de Dados Abertos: https://dadosabertos.camara.leg.br/swagger/api.html#staticfile .

Esses arquivos a que você se refere são da primeira versão dos arquivos de despesas pela Cota Parlamentar. Continuam sendo gerados pela própria área responsável pelos sistemas de gestão da Cota. Nós fizemos a mesma observação sobre o formato e a dificuldade de download dos arquivos, devido ao tamanho, e em 2017 passamos a gerar os arquivos separados por ano e codificados em UTF-8, ainda seguindo a mesma estrutura dos anteriores. Uma nova versão desses arquivos está nos nossos planos.

Obrigado outra vez e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by marcelometal** [comment]
Olá @CeninCD muito obrigado pelas informações, vou usar esse arquivos que você citou!
