### ISSUE TITLE
Site informa que os arquivos são UTF-8, mas na verdade são iso-8859-1

### ISSUE THREAD

**Issue by marcelometal** [labhackercd/dados-abertos#176]
Olá,
Site informa que os arquivos são `UTF-8`, mas na verdade são `iso-8859-1`. Baixei os arquivos aqui:
https://dadosabertos.camara.leg.br/swagger/api.html#staticfile

$  file -i *.json
```
Ano-2009.json: text/plain; charset=iso-8859-1
Ano-2010.json: text/plain; charset=iso-8859-1
Ano-2011.json: text/plain; charset=iso-8859-1
Ano-2012.json: text/plain; charset=iso-8859-1
Ano-2013.json: text/plain; charset=iso-8859-1
Ano-2014.json: text/plain; charset=iso-8859-1
Ano-2015.json: text/plain; charset=iso-8859-1
Ano-2016.json: text/plain; charset=iso-8859-1
Ano-2017.json: text/plain; charset=iso-8859-1
Ano-2018.json: text/plain; charset=iso-8859-1
```

**Comment by CeninCD** [comment]
Olá, Marcelo!

Bug confirmado. Descobrimos onde estava o problema e fizemos a correção. Ainda preciso conferir se a correção já foi colocada em produção hoje pela manhã como estava previsto.

Obrigado pelo aviso! Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by CeninCD** [comment]
Salve, Marcelo!

Os arquivos gerados nessa última madrugada já estão em UTF-8. Por favor confira quando puder.

Obrigado mais uma vez e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by marcelometal** [comment]
Olá Fabricio (@CeninCD),

Esta com utf-8 agora, muito obrigado!
