### ISSUE TITLE
URL não abre a aba de Arquivos 

### ISSUE THREAD

**Issue by marcelometal** [labhackercd/dados-abertos#177]
Olá,
apesar de existir o `#staticfile` na URL, ao entrar pela URL abaixo não sou direcionado para aba de **Arquivos**.

https://dadosabertos.camara.leg.br/swagger/api.html#staticfile

**Comment by CeninCD** [comment]
Salve, Marcelo!

Isso se deve à forma não-padronizada com que os navegadores tratam os "identificadores de fragmento" nas URLs. O que vem depois do # nem é enviado do navegador para o servidor na requisição da página.

É um probleminha bem chato para a divulgação do link para a seção de Arquivos, e nossa equipe não tem especialistas em _frontend_. Talvez seja possível implementar algo na página com Javascript para fazer com que a seção seja exibida quando a página for carregada e houver o _hash_ na página.

Alguém de _frontend_ da comunidade teria uma sugestão??

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by vitormarcal** [comment]
Olá, após carregar o swagger: 
if (window.location.href.endsWith('#staticfile')) $('#staticfileTab').click()

**Comment by CeninCD** [comment]
Salve, Marcelo!

Problema resolvido graças ao Vitor (que é da nossa equipe)!

Obrigado pelo aviso e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by marcelometal** [comment]
valeu! Abração!
