### ISSUE TITLE
[Consulta deputados] Campo de data fora do padrão

### ISSUE THREAD

**Issue by lucamenor** [labhackercd/dados-abertos#179]
Ao consultar um deputado por ID, o modelo da resposta e as versões anteriores retornavam as datas no padrão conforme modelo. Após a última versão está retornando o timestamp (long). Acredito que o mais correto seria seguir o modelo, até porque no modelo tem informação de fuso horário, enquanto o timestamp não.

**Comment by CeninCD** [comment]
Olá, Luca!

Obrigado pelo contato e pelo alerta. Descobrimos na manhã desta segunda-feira o problema, que não está só no _endpoint_ de deputados, mas aparentemente em tudo que é serviço que retorna datas.

A causa foi um conflito do nosso código com uma atualização do _framework_ Spring que utilizamos na API.

Já estamos trabalhando nesse problema e a solução será publicada nas próximas horas.

Obrigado mais uma vez e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by lucamenor** [comment]
Eu que agradeço pelo retorno, Fabricio. Testei aqui, já vi que uma nova versão foi disponibilizada, meu aplicativo voltou a funcionar. Muito obrigado! Não sei se é interesse de vocês, mas caso queiram saber, esse meu aplicativo (https://play.google.com/store/apps/details?id=br.com.lucianomedeiros.eleicoes2018) utiliza tanto essa API da Câmara, quanto do Senado e do TSE. Excelente trabalho de vocês disponibilizando a API, sem ela não poderia ter feito algumas funcionalidades. Parabéns!

Luciano Medeiros
Analisa Judiciário - TJPB

**Comment by CeninCD** [comment]
Salve, Luca!

Depois mande mais informações e gráficos do seu app para o nosso email, para que possamos colocar na seção de projetos da comunidade do nosso portal!

(na verdade, estamos tendo um p*** problema para fazer qualquer atualização no portal... mas uma hora eu consigo.)

Abração e obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara
