### ISSUE TITLE
Busca por mesa de uma legislatura não retorna dados

### ISSUE THREAD

**Issue by brunocramos** [labhackercd/dados-abertos#185]
Boa tarde!

Verifiquei a busca por mesas utilizando `/legislaturas/{id}/mesa`, porém, testando cada legislatura individualmente, nenhuma mesa foi retornada para nenhuma legislatura.
Gostaria de confirmar se o id que deve ser utilizado é, de fato, o da legislatura, ou o do autor, ou se há realmente algum problema.

Obrigado!

**Comment by CeninCD** [comment]
Olá, Bruno!

Na API nova do Dados Abertos o `{id}` no caminho (path) _sempre_ é de um item da _coleção_ a que se refere o elemento anterior do _path_. No caso, sim, o `{id}` é o de alguma legislatura em especial, e o identificador usado é o próprio número da legislatura.

Observe que não temos dados registrados sobre as legislaturas anteriores à 52 (2003 a 2007). Da 52 até a 55, que é a atual, testei aqui e está funcionando. Se você puder, por favor explique em mais detalhes o o problema (como foi feita a requisição, o que você recebeu de resposta, etc).

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by brunocramos** [comment]
Olá, Fabricio!
Obrigado, com sua explicação está tudo certo.
Abs
