### ISSUE TITLE
Author da proposição

### ISSUE THREAD

**Issue by rafaelribeiros** [labhackercd/dados-abertos#186]
Haveria a possibilidade de trazer o autor principal da proposição no endpoint "/proposicoes"?

**Comment by CeninCD** [comment]
Salve, Rafael!

Não há na nossa base algum dado que explicitamente indique quem é um autor principal das proposições. Em tese, o primeiro registro é o do autor principal, mas não é garantido que os autores sejam sempre cadastrados nesta ordem e, pior ainda, na própria busca pelos dados pode haver alguma reordenação que não deixaria essa informação inferida ser confiável.

Os autores hoje estão em um sub-recurso da API porque uma proposição pode ter mais de um autor e optamos por manter estruturas "planas", sem  _arrays_ de objetos aninhados, em prol da compatibilidade com os formatos tabulares dos arquivos para download.

Está na nossa especificação um parâmetro de _query string_ para permitir que, em _endpoints_ como `/proposicoes`, o usuário possa solicitar a inclusão de sub-recursos nos itens retornados. Ou seja, será possível obter, já nessa listagem, os autores de cada proposição. Ainda não há prazo para a implementação desse parâmetro, mas pode ser que ele seja implementado na primeira janela de oportunidade que tivermos.

Abraço e obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by rafaelribeiros** [comment]
Obrigado pela atenção. Ficarei no aguardo da inclusão do parâmetro.
