### ISSUE TITLE
Data de tramitação no futuro

### ISSUE THREAD

**Issue by caioflores** [labhackercd/dados-abertos#191]
Pessoal, não sei se aqui é o melhor lugar para reportar isso, se não for, peço que me avisem como proceder para reportar erros desse tipo.

Encontramos uma tramitação no futuro na MPV 844/2018 na API da Câmara, vocês podem verificar nesse endpoint que a última tramitação possui essa data: https://dadosabertos.camara.leg.br/api/v2/proposicoes/2181294/tramitacoes

**Comment by CeninCD** [comment]
Olá, Caio!

A não ser que estejamos realmente viajando no tempo, isso me parece claramente um erro no registro dos dados no sistema de origem. Vou encaminhar sua descoberta para as áreas responsáveis.

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by caioflores** [comment]
Obrigado pelo retorno! Posso reportar esse tipo de situação de provável inconsistência nos dados aqui no github mesmo?

Nós extraímos diariamente os dados da API da Câmara, consigo até criar um script aqui para identificar esse tipo de coisa se for do interesse de vocês.

**Comment by CeninCD** [comment]
Salve de novo!

Tenho a informação de que o dado já foi corrigido!

A rigor, o canal para uma reclamação dessa natureza seria o _Fale Conosco_ da Câmara, mas aqui mesmo temos a visão de que não deve ser responsabilidade do usuário-cidadão saber se tinha que ligar para X ou mandar e-mail para Y. Esse é um dos pontos do Plano de Dados Abertos que estamos elaborando e formalizando atualmente.

Toda revisão de dados que você e outros usuários puderem fazer será extremamente valiosa não só para o Dados Abertos, mas principalmente para a Câmara, como instituição pública e fonte primária de informação histórica. O que você encontrar de problemas, pode colocar aqui mesmo ou mandar para o nosso e-mail, _dadosabertos.cenin [em] camara.leg.br_.

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by caioflores** [comment]
Muito obrigado pela informação, farei isso!
