### ISSUE TITLE
Endpoint com informações de discursos não retorna NENHUM discurso nos últimos 30 dias

### ISSUE THREAD

**Issue by caioflores** [labhackercd/dados-abertos#194]
Nós capturamos os novos discursos da Câmara diariamente, ontem percebemos que não haviam novos discursos na nossa base desde o dia 1 de novembro. Nós utilizamos a seguinte URL para extrair as informações: https://www.camara.leg.br/sitcamaraws/SessoesReunioes.asmx/ListarDiscursosPlenario?dataIni=14/10/2018&dataFim=14/11/2018&codigoSessao=&parteNomeParlamentar=&siglaPartido=&siglaUF=

**Comment by CeninCD** [comment]
Olá, Caio!

Confirmamos que há na base de dados de discursos itens mais recentes, até 08 de novembro. Fizemos alguns testes no _webservice_ e ainda não conseguimos descobrir o que está causando o problema. Assim que houver atualização aviso aqui.

Obrigado pelo relato e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by caioflores** [comment]
Olá @CeninCD  houve algum avanço nesse bug? Preciso reportar os nossos clientes sobre o status dos discursos. Podemos ajudar de alguma maneira?

**Comment by CeninCD** [comment]
Olá, Caio!

Desculpe a demora na resposta -- eu estava esperando que _houvesse_ uma resposta antes de escrever. Testamos hoje o _webservice_ e aparentemente o funcionamento voltou ao normal. Houve uma atualização recente do sistema de registros de discursos, que incluiu uma mudança na utilização da base de dados sobre a qual não fomos informados previamente. 

Caso você detecte algum problema ou algo fora do esperado, por favor avise outra vez.

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by caioflores** [comment]
Obrigado pelo retorno @CeninCD ! Aparentemente está tudo ok! 
Abraços.
