### ISSUE TITLE
/deputados/{id} - No ultimoStatus, campo "situacao" não disponível quando condicaoEleitoral é "Eleito"

### ISSUE THREAD

**Issue by jeslopes72** [labhackercd/dados-abertos#207]
Em https://dadosabertos.camara.leg.br/api/v2/deputados/74159:
```
<xml>
  <dados>
    <id>74159</id>
...    <ultimoStatus>
      <id>74159</id>
...
      <situacao/>
      <condicaoEleitoral>Eleito</condicaoEleitoral>
      <descricaoStatus/>
    </ultimoStatus>
...
</xml>
```

Mas vemos o deputado em exercício em http://www.camara.leg.br/internet/deputado/Dep_Detalhe.asp?id=74159

Para deputados não eleitos, a "situacao" vem com a informação correta (ex. "Exercício") e a condicaoEleitoral vem com a distinção entre Titular e Suplente.

**Comment by CeninCD** [comment]
Olá, João!

Obrigado pela oportunidade de explicar isso aqui no GitHub para que os demais usuários vejam -- já tivemos outros questionamentos semelhantes, e por isso mesmo eu _achei_ que já tinha respondido ao seu e-mail anterior...

Fomos pegos de surpresa pelo cadastramento antecipado, na base, dos deputados eleitos para a legislatura 56. O deputado que você mencionou, e vários outros, está em exercício **pela legislatura 55**. Mas por causa do cadastramento antecipado, o `ultimoStatus` retornado já é o da legislatura que ainda não começou (observe o campo `idLegislatura`) -- e como a legislatura não começou, o deputado ainda não tem uma `situação` nela: apenas a `condicaoEleitoral` de eleito.

Esse condicionamento é importante porque é comum que candidatos eleitos sejam convidados a assumir ministérios e secretarias, e nesses casos eles não chegam a tomar posse. Isso já ocorreu com alguns candidatos que foram eleitos pela primeira vez e até foram cadastrados na base, mas jamais chegaram a tomar posse -- por isso, no Dados Abertos, eles não são considerados deputados.

Já fizemos uma alteração no código para que a API não retorne essas informações pré-cadastradas, mas ainda não foi publicada por um enrosco no nosso ciclo de lançamentos que estamos tentando resolver. 

Abraço, desculpe pelo problema e obrigado mais uma vez!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by jeslopes72** [comment]
Valeu Fabricio. Vamos considerar resolvido então.
