### ISSUE TITLE
Dados sobre a votação das proposições

### ISSUE THREAD

**Issue by tiagooc10** [labhackercd/dados-abertos#21]
Olá, eu não estou conseguindo obter os dados sobre as votações por meio das consultas, eles estão indisponíveis ?

**Comment by RodolfoViana** [comment]
Oi, é possível obter os dados da votações por meio de consultas, faço isso semanalmente. Como que você tá fazendo essas consultas?

**Comment by anchaves** [comment]
Olá, alguém conhece um site que compila as votações dos parlamentares por assunto?

**Comment by RodolfoViana** [comment]
Talvez você encontra algo útil nesses dois sites http://www.atlaspolitico.com.br/mapa-congresso http://houseofcunha.com.br/

**Comment by diraol** [comment]
​No Radar Parlamentar (http://radarparlamentar.polignu.org) você consegue
visualizar a análise filtrando por tema/assunto...

**Comment by labhacker** [comment]
@tiagooc10, estou encerrando a issue, mas caso continue com dúvidas, sinta-se à vontade em responder aqui. 

Atenciosamente,

Pedro Brandão
Laboratório Hacker
