### ISSUE TITLE
API retorna 404 em /votacoes/7937/votos

### ISSUE THREAD

**Issue by hadrizia** [labhackercd/dados-abertos#212]
Olá dados abertos, a votação 7937 existe e pode ser encontrada em https://dadosabertos.camara.leg.br/api/v2/proposicoes/2156331/votacoes. Mas ao tentar acessá-la, recebo um erro 404 com a mensagem 'A URL passada se refere a um recurso que não existe no sistema.' Eis o endpoint: https://dadosabertos.camara.leg.br/api/v2/votacoes/7937

**Comment by CeninCD** [comment]
Olá, Hadrizia!

Continua o aviso a todos os usuários: **ignore _qualquer_ informação sobre votações na nova API.** Essa URL é inválida já na geração, porque na verdade não existe ainda um identificador exclusivo para cada votação realizada na Câmara.

(!)

Também não há, ainda, a identificação correta da proposição que é _realmente votada_ em cada votação. Normalmente, a votação do PL XYZ é acompanhada da votação de requerimentos, destaques, emendas, etc relacionados ao projeto -- mas todas essas votações são cadastradas como votação do próprio PL XYZ. Não há nada de informação estruturada que permita identificar qual dessas votações foi a do PL XYZ propriamente dito e qual foi de uma proposição acessória.

(!!!)

Enquanto vamos implementando e corrigindo outras coisas menos enroladas na API e nos arquivos, ainda fazemos algumas experiências para tentar achar uma forma de publicar os dados de votações de maneira pelo menos _aceitável_, já que as áreas que têm autoridade sobre esses dados não oferecem uma solução.

Desculpe pelo problema e pelo desabafo. Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
