### ISSUE TITLE
Página para baixar os arquivos da CEAP deastualizada?

### ISSUE THREAD

**Issue by cuducos** [labhackercd/dados-abertos#216]
Boa tarde,

Reparei que [nessa página](http://www2.camara.leg.br/transparencia/cota-para-exercicio-da-atividade-parlamentar/dados-abertos-cota-parlamentar) só aparecem os links para download dos arquivos da CEAP até o ano de 2017. Os links para 2018 e 2019 funcionam, mas não estão listados ali.

Existe algum motivo para isso? Existe uma outra página com esses links atualizados?

Muito obrigado,

**Comment by vitormarcal** [comment]
Olá, você também pode encontrar na [área de arquivos dos Dados Abertos](https://dadosabertos.camara.leg.br/swagger/api.html#staticfile):

**Comment by cuducos** [comment]
Ah! Perfeito. Muito obrigado, @vitormarcal ; )
