### ISSUE TITLE
Diferenciação entre autores e coautores de proposições de lei

### ISSUE THREAD

**Issue by lucaslrolim** [labhackercd/dados-abertos#217]
Olá,

Gostaria de saber se existe alguma forma de diferenciar quem são os autores principais e quem são os co-autores de uma proposição de lei. Atualmente todos os dados sobre autoria são retornados da mesma forma, com as mesmas tags XML ou dentro do mesmo objeto no JSON.

Um exemplo é a seguinte rota:

https://dadosabertos.camara.leg.br/api/v2/proposicoes/2174758/autores?formato=json

**Comment by CeninCD** [comment]
Salve, Lucas!

Não é a melhor forma (nem sequer a correta), mas você pode inferir esta informação pelo posicionamento de cada autor na lista retornada -- que é a mesma ordem com a qual os autores de cada proposição são cadastrados na base. O primeiro é o "autor principal". Devo ressalvar que isso pode ser problemático especificamente com JSON, que por especificação não tem listas ordenadas.

Está no nosso radar incluir no retorno, de forma explícita, essa "ordenação" dos autores, mas ainda precisamos confirmar os critérios e a validade dessa classificação na base, para evitar problemas.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by lucaslrolim** [comment]
Obrigado! Fico no aguardo. Pretendo escrever uma artigo modelando a rede de coautoria da câmara e essa informação seria de grande valia.
