### ISSUE TITLE
Dúvida sobre alteração de proposições retroativa

### ISSUE THREAD

**Issue by kerollaine** [labhackercd/dados-abertos#22]
Olá!
Tenho uma dúvida sobre Proposições > operação 'listarProposicoesTramitadasNoPeriodo'. Se eu chamá-lo eu corro o risco de não obter uma proposição que poderia ser inserida futuramente (de forma retroativa)? 

Por exemplo, busquei entre o intervalo de datas x a y, e não tinha a tramitação Z. Depois de alguns dias, a tramitação Z foi inserida no intervalo de x a y, mas este intervalo já passou.. É possível que apareçam informações de maneira retroativa?

**Comment by labhacker** [comment]
Ficamos gratos por enviar a dúvida, @kerollaine! Infelizmente não sei respondê-la de imediato, então vou manter a issue aberta.

Temos o compromisso de fomentar o uso dos dados abertos, mas também está claro que há questões de qualidade que precisam ser abordadas. 

Ontem nos reunimos com diversos setores técnicos envolvidos na disponibilização dos dados abertos e discutimos melhores mandeiras de atender às tantas demandas registradas.

Podem ficar tranquilos, pois estamos avaliando o que pode ser feito em âmbito institucional. Postaremos updates à medida que fizermos progresso. :-)

Pedro Brandão
Laboratório Hacker

**Comment by CeninCD** [comment]
Bom dia a todos.

A convite do LabHacker, estamos nos juntando a vocês neste fórum. Vamos buscar a solução de bugs e o esclarecimento de dúvidas na utilização dos dados abertos da Câmara dos Deputados. 

Esclareço que, infelizmente, nossa capacidade de atender às demandas está reduzida. Estamos trabalhando para que tenhamos uma equipe mais robusta para manter e evoluir os dados abertos a partir de 2017, para viabilizar projetos maiores.

Neste momento, algumas coisas podem demorar um pouco, outras não conseguiremos implementar, mas vamos procurar sempre estar por aqui, atender o que for possível e informar quando não for.

Quanto a sua dúvida, @kerollaine: sim, é possível que sejam registradas tramitações em datas passadas. Isso pode acontecer, por exemplo, nas tramitações que acontecem fora da Câmara (como as que ocorrem no Senado, ou a sanção e publicação quando se transforma em norma) e naquelas que não são completamente automatizadas, como alguns registros feitos pelas comissões. Considere essa característica no desenho da sua aplicação.

Atenciosamente,

Paulo Henrique
Centro de Informática

**Comment by kerollaine** [comment]
Obrigada, pessoal!
