### ISSUE TITLE
Servidor fora do ar?

### ISSUE THREAD

**Issue by junioregis** [labhackercd/dados-abertos#26]
não estou conseguindo obter deputados. alguém aí consegue?

**Comment by geraugu** [comment]
tbm nao, está fora desde o meio da semana.

**Comment by junioregis** [comment]
oooo no! :(

**Comment by fguimaraesbh** [comment]
WebService de Proposições também está fora do ar: http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx
Alguma previsão de retorno?
Obrigado!

**Comment by fguimaraesbh** [comment]
Parece que voltou.

**Comment by CeninCD** [comment]
Boa tarde.

O serviço está funcionando normalmente hoje. Solicitamos a verificação de incidentes nos últimos dias, mas não identificaram algo que explicasse a indisponibilidade do serviço.

Peço que, caso voltem a observar o problema, nos passem informações mais detalhadas, como o endpoint que estavam tentando acessar, data e horário e o erro retornado.

Atenciosamente,

Paulo Henrique
Centro de Informática

**Comment by labhacker** [comment]
Prezados, agradecemos as contribuições! Como o problema foi sanado, estou fechando a issue.

Att.,

Pedro Brandão
Laboratório Hacker
