### ISSUE TITLE
autores dos proposições é incompleto

### ISSUE THREAD

**Issue by ajanman** [labhackercd/dados-abertos#28]
Parece que muitos dos projetos de lei falta informaçao completo dos autores.  

Um exemplo é PL 1517/1999. O website da Camara diz que o projeto so tem um autor (ALBERICO CORDEIRO), mas o Diário de Câmara diz "ALBERICO CORDEIRO E OUTROS" (59 outros). 

Esses dados são acessíveis em outro lugar do website?

**Comment by CeninCD** [comment]
Bom dia, @ajanman.

Encaminhei sua dúvida para a equipe responsável. Suspeito que, em função de ser uma proposição relativamente antiga (1999), isso se deva a limitações do sistema à época. Mas estou checando.

Paulo Henrique
Centro de Informática

**Comment by CeninCD** [comment]
Bom dia, @ajanman. 

À época do registro dessa proposição, o sistema legislativo ainda não permitia o registro de coautoria. Essa informação passou a ser registrada em formato estruturado em 2006. Algumas proposições anteriores a essa mudança foram editadas sob demanda para incluir os coautores. Mas, via de regra, elas mantiveram apenas um autor.

Desculpe a demora para responder.

Paulo Henrique
Centro de Informática
