### ISSUE TITLE
Servidor fora do ar

### ISSUE THREAD

**Issue by junioregis** [labhackercd/dados-abertos#29]
Estou tentando acessar "http://www.camara.gov.br/SitCamaraWS/Deputados.asmx/ObterDeputados" neste exato momento e está me retornando o erro:

503 Service Unavailable
No server is available to handle this request.

**Comment by junioregis** [comment]
Parece que o servidor ainda está fora do ar. Alguma notícia?

**Comment by CeninCD** [comment]
Bom dia, @junioregis.

Houve uma manutenção nos nossos servidores neste final de semana e ela gerou impactos imprevistos, incluindo a interrupção de alguns serviços. A princípio, todos já foram restabelecidos. Se observar a persistência de algum problema, por favor, nos informe.

Desculpe pelos inconvenientes. 

Paulo Henrique
Centro de Informática
