### ISSUE TITLE
Falta de item urlFoto na documentação de "obter deputados"

### ISSUE THREAD

**Issue by UlyssesRocha** [labhackercd/dados-abertos#33]
Caros, 
Notei uma falha na documentação presente no [link ](http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/deputados/obterdeputados), o mesmo não informa a presença do campo **urlFoto** no XML, o que me fez perder bastante tempo procurando onde poderia encontrar este dado.

Recomendo alteração na documentação da pagina, informando a presença do campo no XML.

Aproveitando o issue, gostaria de recomendar também a presença da foto em uma maior resolução na ação de **ObterDetalhesDeputado**.

Att,

**Comment by CeninCD** [comment]
@UlyssesRocha, a documentação de ObterDeputados foi atualizada. Obrigado pelo alerta.

Quanto a fotos com maior resolução, não dispomos para publicação (seja no portal ou nos web services). Vou encaminhar a sugestão internamente.

Paulo Henrique
Centro de Informática
