### ISSUE TITLE
[Duvida] Obter dados da Cota Parlamentar

### ISSUE THREAD

**Issue by UlyssesRocha** [labhackercd/dados-abertos#34]
Caros,
Encontrei apenas uma forma de obter os dados da Cota Parlamentar, através do [link ](http://www2.camara.leg.br/transparencia/cota-para-exercicio-da-atividade-parlamentar/dados-abertos-cota-parlamentar), mas é impraticável para minha aplicação o download de um .zip e extrair informações de um XML enorme.

A pergunta que fica é, existe alguma alternativa que não seja parse do HTML de paginas como [essa](http://www.camara.gov.br/cota-parlamentar/cota-sumarizado?nuDeputadoId=3074&mesAnoConsulta=1-2016) para obter as informações de cota parlamentar de um especifico deputado ? Existe alguma forma de acesso direto aos dados sem ser por esse .zip?

**Comment by CeninCD** [comment]
Bom dia, @UlyssesRocha.

A única forma de que dispomos atualmente para publicar as informações sobre cota parlamentar em dados abertos são os arquivos XML zipados no endereço que você citou. Não há web services para essa base de dados.

Uma opção à raspagem das páginas seria você montar uma base de dados própria com os arquivos, atualizando-a diariamente. 

Acreditamos que o ideal seja oferecer os dados tanto via arquivos quanto via web services. Mas, infelizmente, não temos como implementar novos mecanismos neste momento.

Peço ao @labhacker  para registrar no nosso backlog.

Paulo Henrique
Centro de Informática

**Comment by labhacker** [comment]
OK, sugestão adicionada ao backlog.

Pedro Brandão
Laboratório Hacker
