### ISSUE TITLE
Proposições com nome no formato PDC 563/2008 => MSC 711/2007

### ISSUE THREAD

**Issue by leonardofl** [labhackercd/dados-abertos#41]
Olá,

ao invocar 

http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoes?sigla=PDC&numero=&ano=2008

temos algumas proposições com o nome fora do padrão, tipo PDC 563/2008 => MSC 711/2007.

Para obter as votações dessa proposição, devemos acessar a URL

http://www.camara.gov.br/sitcamaraws/Proposicoes.asmx/ObterVotacaoProposicao

Mas essa consulta não pode ser feita por id (certo?). Ela exige sigla/número/ano.

Como eu deveria invocar ObterVotacaoProposicao para obter os dados das votações de PDC 563/2008 => MSC 711/2007 (id 394337)? 

Talvez não seria implementar um acesso via ID? (http://www.camara.gov.br/sitcamaraws/Proposicoes.asmx/ObterVotacaoProposicao?id=394337)

E aliás, o que significa essa seta? A proposição mudou de nome ou algo assim?

Grato!

Referência: http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/proposicoes-1/obtervotacaoproposicao

**Comment by DaniloOliveira28** [comment]
Olá @leonardofl ,

Há um método, não documentado, que permite a obtenção da votação por id. Veja:

http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ObterVotacaoProposicaoPorID?idProposicao=394337

http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx

Att.
Danilo

**Comment by DaniloOliveira28** [comment]
A seta tem significado dentro do contexto do Processo Legislativo. Por ex.: 
O PDC 563/2008 é um projeto de decreto legislativo, ou seja, uma proposição (Regimento Interno Art. 100. Proposição é toda matéria sujeita à deliberação da Câmara.) que foi originada da MSC 711/2007 que foi um acordo fechado por algum diplomata Brasileiro.

Ou seja, um diplomata fechou um acordo no exterior. enviou uma mensagem para a Presidente informando sobre o acordo. O Presidente encaminhou a mensagem para o Congresso para ratificação, gerando o PDC.

**Comment by leonardofl** [comment]
Opa, grato!
Acho que podemos considerar a issue resolvida, embora fosse legal documentar o recurso não documentado ;)
