### ISSUE TITLE
"Response" para download informa tipo errado do documento a ser baixado

### ISSUE THREAD

**Issue by urbanobm** [labhackercd/dados-abertos#44]
Bom dia!

Está acontecendo em algumas matérias que o "response" recebido de uma requisição para download de um documento informa um tipo errado do documento a ser baixado.

Por exemplo, a matéria acessado pelo link abaixo: 
http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ObterProposicaoPorID?idProp=2083581

indica este outro link para baixar um documento e a resposta deste link informa que o arquivo a ser baixado é do tipo "text/html; charset=iso-8859-1" quando na verdade é um do tipo "doc":
www.camara.gov.br/proposicoesWeb/prop_mostrarintegra?codteor=1455399

Casos semelhantes aconteceram também quando o "response" informava que o arquivo era do tipo "text/html; charset=iso-8859-1" e na verdade o arquivo a ser baixado era um PDF. Segue um exemplo:
http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ObterProposicaoPorID?idProp=2083005
http://www.camara.gov.br/proposicoesWeb/prop_mostrarintegra?codteor=1454207

Gentileza verificar.
Obrigado.

**Comment by CeninCD** [comment]
Olá, Urbano!

Obrigado pelo aviso!

Acabei de tentar reproduzir as falhas relatadas e não consegui. No link de "inteiro teor" da primeira proposição, o cabeçalho de resposta veio com uma linha `Content-Type: application/msword`. Com o segundo link, do arquivo em PDF, o _response header_ veio com `Content-Type: application/pdf` conforme o esperado.

Por favor, tente fazer um novo teste, preferencialmente com uma ferramenta como SoapUI, Postman ou cURL, e nos avise sobre os resultados para que tentemos descobrir o que aconteceu.

Obrigado e abraço!

Fabricio Rocha
Centro de Informática
Câmara dos Deputados
