### ISSUE TITLE
ListarProposicoesTramitadasNoPeriodo não lista todas?

### ISSUE THREAD

**Issue by wagnerrt** [labhackercd/dados-abertos#45]
A matéria id 2055351 (PL 3637/2015):
[(http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao=2055351)](http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao=2055351)
teve andamento hoje, 19/05/2016:
[http://www.camara.gov.br/SitCamaraWS/Orgaos.asmx/ObterAndamento?sigla=PL&numero=3637&ano=2015&dataIni=&codOrgao=](http://www.camara.gov.br/SitCamaraWS/Orgaos.asmx/ObterAndamento?sigla=PL&numero=3637&ano=2015&dataIni=&codOrgao=) )
mas o andamento não foi anunciado no endpoint ListarProposicoesTramitadasNoPeriodo:
[http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoesTramitadasNoPeriodo?dtInicio=19/05/2016&dtFim=19/05/2016](http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoesTramitadasNoPeriodo?dtInicio=19/05/2016&dtFim=19/05/2016)

Falha no sistema ou na minha interpretação da API?

**Comment by wagnerrt** [comment]
Acabo de descobrir que a situação é um pouco mais crítica do que eu achava. Na listagem das atualizações do dia 20/05/2016 a movimentação esperada ainda não aparece:
[http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoesTramitadasNoPeriodo?dtInicio=20/05/2016&dtFim=20/05/2016](http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoesTramitadasNoPeriodo?dtInicio=20/05/2016&dtFim=20/05/2016)
No entanto, se for solicitado o movimento a partir de 19/05 até o dia 20/05 o registro esperado aparece:
[http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoesTramitadasNoPeriodo?dtInicio=19/05/2016&dtFim=20/05/2016](http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoesTramitadasNoPeriodo?dtInicio=19/05/2016&dtFim=20/05/2016)
`<proposicao>
<codProposicao>2055351</codProposicao>
<tipoProposicao>PL</tipoProposicao>
<numero>3637</numero>
<ano>2015</ano>
<dataTramitacao>19/5/2016 17:23:00</dataTramitacao>
<dataAlteracao>19/5/2016 17:23:25</dataAlteracao>
</proposicao>`
`<proposicao>
<codProposicao>2055351</codProposicao>
<tipoProposicao>PL</tipoProposicao>
<numero>3637</numero>
<ano>2015</ano>
<dataTramitacao>19/5/2016 17:25:00</dataTramitacao>
<dataAlteracao>19/5/2016 17:25:20</dataAlteracao>
</proposicao>`

**Comment by CeninCD** [comment]
Bom dia, @wagnerrt.

Encaminhei esse incidente internamente. Parece haver mesmo uma falha na consulta do método ListarProposicoesTramitadasNoPeriodo. Testamos a consulta às tramitações com início e fim no dia 19 e depois com início em 19 e fim no dia 20/05. A tramitação do PL 3737/2015 no dia 19 só aparece na segunda consulta e outras tramitações no dia 19 aparecem na primeira (como a de ID 2017042).

Assim que tivermos um retorno, informamos aqui.

Paulo Henrique
Centro de Informática

**Comment by wagnerrt** [comment]
Bom dia, Paulo Henrique.

Agradeço imensamente a análise do caso. Informo que o sistema que utiliza esse serviço mantém as matérias em cache no banco próprio e faz atualização apenas quando estas sofrem andamento, portanto considero crítico para a aplicação e benéfico à Câmara.

Fico no aguardo de instruções sobre o que fazer.

**Comment by CeninCD** [comment]
Bom dia, @wagnerrt .

A falha no método foi corrigida. Favor verificar.

Caso ainda persista o problema, por favor, nos informe.

Paulo Henrique
Centro de Informática

**Comment by wagnerrt** [comment]
Obrigado! Para a situação identificada no caso em questão, resolveu perfeitamente. Continuarei atento e relatando qualquer dúvida que tiver. Abraço e parabéns pelo trabalho de excelência que a Câmara está fazendo nessa área.
