### ISSUE TITLE
Erro ao chamar API de Órgãos (ObterPauta)

### ISSUE THREAD

**Issue by fernandosiq** [labhackercd/dados-abertos#50]
Consultando a API de Órgaos, no método ObterPauta,

Passando
 `<org:IDOrgao>4</org:IDOrgao>`
Estou recebendo o seguinte erro:
`faultstring>Cast from type 'DBNull' to type 'String' is not valid. - Microsoft.VisualBasic -    at Microsoft.VisualBasic.CompilerServices.StringType.FromObject(Object Value)
   at CamaraWSSemComponente.Orgaos.ObterPauta(Int32 IDOrgao, String datIni, String datFim)</faultstring>
         <faultactor>ObterPauta</faultactor>`

**Comment by fernandosiq** [comment]
Oi Fabricio,

Testando com outros ID (537388), funciona, porém existe um órgão de ID 4, correto?
`<orgao id="4" idTipodeOrgao="1" sigla="MESA      " descricao="Mesa Diretora da Câmara dos Deputados"/>`

De qualquer modo, obrigado, pois já resolve parte do meu problema.

**Comment by CeninCD** [comment]
Salve, Fernando!

Verdade, verdade -- você vê, a falta de ordenação e critérios claros nos dados atrapalha a gente também!

Mesmo assim... Eu já havia testado o endpoint usando "4" como valor para `&IDOrgao` e ele funcionou corretamente. Por isso eu gostaria de ver qual foi a URL de requisição que gerou o erro...

Obrigado!

Fabricio Rocha
Centro de Informática da Câmara

**Comment by fernandosiq** [comment]
Fabricio,

Pelo SOAP-UI
![image](https://cloud.githubusercontent.com/assets/9454880/16812749/e8130d12-4904-11e6-9406-b91c056ea19f.png)

Pelo browser
![image](https://cloud.githubusercontent.com/assets/9454880/16812886/86b8dd5c-4905-11e6-8ad7-a983c779a789.png)

Vendo agora, demora um bocado de tempo para retornar,
Pode ser que seja alguma coisa relacionada a timeout.

**Comment by dschwabe** [comment]
Boa tarde,
gostaria de saber se exiiste algum serviço que me retorne os dados de um deputado eleito para a legislatura atual mas que não esteja no exercício (p.ex., Sarny Filho).
Grato,

Daniel Schwabe                      Dept. de Informatica, PUC-Rio
Tel:+55-21-3527 1500 r. 4356        R. M. de S. Vicente, 225
Fax: +55-21-3527 1530               Rio de Janeiro, RJ 22453-900, Brasil
http://www.inf.puc-rio.br/~dschwabe

**Comment by CeninCD** [comment]
Olá, Fernando!

Pela imagem do browser que você mandou, consegui reproduzir o erro. Não parece ser um problema de _timeout_ não, e sim de algum registro na base de dados contendo um valor que não foi reconhecido como válido para ser convertido para string. Vamos encaminhar a reclamação internamente e assim que possível atualizo a situação por aqui. Obrigado pelo aviso.

Prof. Daniel, não há realmente no momento um serviço que forneça dados sobre deputados afastados, licenciados, etc. Existem algumas reclamações a respeito disso e vamos pensar numa solução para a próxima atualização do Dados Abertos. Desculpe e mantenha contato!

Fabricio Rocha
Centro de Informática da Câmara

**Comment by CeninCD** [comment]
Olá de novo, senhores!

O problema foi corrigido. Havia um mau funcionamento na interpretação dos parâmetros de datas.

A correção também alterou o comportamento do serviço: agora, quando não são passados valores para os parâmetros _datIni_ e _datFim_, eles assumem como valor padrão a data _do momento da chamada_.

Mais uma vez obrigado e abraços!

Fabricio Rocha
Centro de Informática da Câmara
