### ISSUE TITLE
O nome do deputado Matheus Iensen está errado

### ISSUE THREAD

**Issue by vitorbaptista** [labhackercd/dados-abertos#7]
No banco de dados ele está como Math**ue**s Iensen, ao invés de Math**eu**s Iensen

**Comment by labhacker** [comment]
Vitor, poderia nos fornecer uma chamada que retorne o nome do deputado incorretamente? 

Grato,

Pedro Brandão
Laboratório Hacker

**Comment by vitorbaptista** [comment]
Claro!

http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ObterVotacaoProposicao?tipo=PL&numero=1793&ano=1991

Se precisar de outras, em https://github.com/vitorbaptista/dados-abertos-camara.gov.br há um dump das votações das proposições. Lá existem 74 votos de "Mathues Iensen".

**Comment by CeninCD** [comment]
Boa tarde, @vitorbaptista!

O nome do parlamentar foi corrigido nas bases de votações. Favor verificar se restou alguma inconsistência. 

Atenciosamente,

Paulo Henrique
Centro de Informática

**Comment by vitorbaptista** [comment]
Até onde eu pude ver, o problema foi corrigido. Obrigado, Paulo! :+1:
