### ISSUE TITLE
WebService para Gastos dos Deputados está quebrado

### ISSUE THREAD

**Issue by victorximenis** [labhackercd/dados-abertos#71]
O serviço sempre retorna erro 500 para as solicitações.

Requisição:

GET https://dadosabertos.camara.leg.br/api/v2/deputados/178825/despesas

Retorno:

`{
    "status": 500,
    "title": null,
    "detail": "Erro - Contate o Administrador",
    "instance": null,
    "code": null
}`

**Comment by CeninCD** [comment]
Corrigido, Victor! Obrigado pelo alerta! Houve um problema de acesso entre nossa aplicação e o servidor de dados...

Abraço!

Fabricio Rocha
Equipe de Dados Abertos
