### ISSUE TITLE
Dados sobre discursos na nova API

### ISSUE THREAD

**Issue by msfernandes** [labhackercd/dados-abertos#79]
Olá! Eu queria muito migrar pra nova API, mas acabei de ver que ainda não tem os dados de Discursos nela. Alguma previsão?

Preciso dessas informações pro meu TCC :(

**Comment by CeninCD** [comment]
Salve de novo, Matheus!

Estão previstos na nova API os endpoints `/deputados/{id}/discursos` e `/eventos/{id}/discursos` . Ainda não foram implementados por pura e simples limitação de recursos, mas sua demanda ajuda a dar prioridade a eles.

Como você tem urgência, pode obter os discursos feitos no Plenário usando a API antiga, apesar de os métodos serem meio diferentes e os textos estarem disponíveis em formato RTF codificado em Base64. Dê uma olhada nos métodos SOAP descritos em http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/sessoesreunioes-2/sessoesreunioes-1 . 

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by morais90** [comment]
@FabricioRocha você sabe me informar em qual pé está essa issue?

**Comment by EquipeDadosAbertosCD** [comment]
Salve, Willian!

Está em operação o endpoint `/deputados/{id}/discursos`, e ainda não foi implementado o endpoint `/eventos/{id}/discursos`.  O caso desse segundo endpoint tem sido complicado pelo fato de, nas reuniões em comissões, os discursos serem cadastrados em bloco, e não individualizados.

Não sei se era isso que você queria saber, mas é isso...

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by morais90** [comment]
Obrigado pela resposta! Estava querendo utilizar o `/deputados/{id}/discursos`, achei que não estava funcionando.

Peguei uns discursos mais antigos para testar e não está retornando nada.

[DIS 6269/2003](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=137886) - (Paulo Marinho - PL/MA) https://dadosabertos.camara.leg.br/api/v2/deputados/74448/discursos/

[DIS 4417/2003](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=127888) - (Romel Anizio - PP/MG) https://dadosabertos.camara.leg.br/api/v2/deputados/74759/discursos/

[DIS 1703/2003](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=114380) - (Alice Portugal - PCdoB/BA) https://dadosabertos.camara.leg.br/api/v2/deputados/74057/discursos/

**Comment by EquipeDadosAbertosCD** [comment]
Resposta em duas etapas para deixar bem clara a separação: uma institucional e outra bem pessoal...

Antes, objetivamente: sem parâmetros de tempo, o endpoint de discursos retornará somente os discursos ocorridos nos **últimos sete dias**. 

Aqui termina a parte institucional. ;)

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by FabricioRocha** [comment]
Aqui a visão pessoal:

Não se oriente por _discursos_ cadastrados na base de dados de _proposições_ que você tenha obtido pelo Portal. Para pegar leve, vou dizer apenas que, na minha opinião, quem fez isso um dia estava _inspirado_....

Abraço!

Fabricio Rocha
Cidadão
;)
