### ISSUE TITLE
Detalhes de um deputado (/deputados/{id})

### ISSUE THREAD

**Issue by dschwabe** [labhackercd/dados-abertos#81]
Nesta chamada, na API antiga (ObterDetalhesDeputado) é possível passar a legislatura como parametro (opcional), o que não é possível na versão 2. Sugiro adicionar este parâmetro nesta chamada da API v. 2.
Adicionalmente, a chamada na API antiga retornava mais informações, incluindo o histórico de movimentação do parlamentar. Sugiro que ou se incluam estas infos no resultado da chamada atual, ou se crie chamadas adicionais na API que forneçam estas informações, como foi feito, p. ex., para a participação em comissões.

Obrigado,
Daniel

**Comment by CeninCD** [comment]
Olá, Daniel! Como vai?

Tudo isso que você pediu já está presente ou previsto na nova API, embora de maneira diferente e mais uniforme. Para obter a lista dos deputados da legislatura 43, por exemplo, você usa GET https://dadosabertos.camara.leg.br/api/v2/deputados?idLegislatura=43 . Da lista resultante, você pode usar o campo <uri> de qualquer dos itens para obter as informações detalhadas.

Outras informações sobre os parlamentares serão disponibilizadas quando conseguirmos implementar os endpoints previstos na especificação atual, e outros que venham a ser sugeridos pelos usuários. É o caso do endpoint `/deputados/{id}/historico`, que deverá retornar cada uma das mudanças de informação que podem ocorrer com um parlamentar durante o mandato: troca de partido, troca de nome parlamentar, licenças, etc. Além deste, estão previstos mas ainda não implementados os seguintes endpoints sobre deputados:

- /deputados/{id}/numeros
- /deputados/{id}/relatorias
- /deputados/{id}/discursos

Sugestões e pedidos por outras informações são bem vindos!

Abraços!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by dschwabe** [comment]
Olá Fabricio,
obrigado pela pronta resposta. Fico contente que a opção de legislatura já está implementada, mas a documentação online do endpoint (https://dadosabertos.camara.leg.br/swagger/api.html) não informa isto... até tentamos para ver se funcionava, mas "chutamos" a sintaxe errada e deu erro ;-).
Entendo, de qq forma, que a API v.1 continuará disponível por um bom tempo, até que tudo seja disponibilizado na v.2, certo?
Obrigado, e continue o belo trabalho que vcs estão fazendo!

**Comment by CeninCD** [comment]
Olá, prof!

A informação está lá na página do Swagger, sim.... na seção "Deputados", dentro de "GET /deputados". Podem ser passados números de mais de uma legislatura, separados por vírgulas. 

Sim, a API anterior em SOAP continuará funcional por tempo indeterminado. Ela só não terá mais acréscimo de funcionalidades, devido à natural limitação de recursos, que agora estão direcionados para a nova API.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
