### ISSUE TITLE
Inconsistência nas referências next, self e last na função /votacoes/{id}/voto

### ISSUE THREAD

**Issue by paul0vinicius** [labhackercd/dados-abertos#95]
Olá, ao executar um ```GET``` fazendo chamada a esse método ```/votacoes/{id}/voto``` as referências parecem estar incorretas e apontam para um link inexistente.

Por exemplo, ao fazer: 
```curl -X GET "https://dadosabertos.camara.leg.br/api/v2/votacoes/6531/votos?itens=513" -H  "accept: application/json"``` ele retorna um _json_ contendo _dados_ e _links_.

Os links retornados aparecem dessa forma:
```
"links": [
    {
      "rel": "self",
      "href": "https://dadosabertos.camara.leg.br/api/v2/votacoes/6531/votos?itens=513"
    },
    {
      "rel": "next",
      "href": "https://dadosabertos.camara.leg.br/api/v2/votacoes/?/votosid=6531pagina=2&itens=100"
    },
    {
      "rel": "first",
      "href": "https://dadosabertos.camara.leg.br/api/v2/votacoes/?/votosid=6531pagina=1&itens=100"
    },
    {
      "rel": "last",
      "href": "https://dadosabertos.camara.leg.br/api/v2/votacoes/?/votosid=6531pagina=5&itens=100"
    }
  ]
```
E ao tentar acessar qualquer um destes, exceto o _self_, retorna:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<erroCorpo>
<status>404</status>
<title>Recurso não encontrado</title>
<detail>
A URL passada se refere a um recurso que não existe no sistema.
</detail>
<instance>
https://dadosabertos.camara.leg.br/api/v2/votacoes/
</instance>
<code/>
</erroCorpo>
```

Aparenta ser uma inconsistência na construção das URLS:
O formato de ```https://dadosabertos.camara.leg.br/api/v2/votacoes/6531/votos?itens=513``` difere de ```https://dadosabertos.camara.leg.br/api/v2/votacoes/?/votosid=6531pagina=2&itens=100```

**Comment by CeninCD** [comment]
Olá, Paulo!

Sim, claramente os links estão malformados. Obrigado pelo aviso e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by CeninCD** [comment]
Olá, Paulo!

Você pode, por favor, conferir se a versão 0.2.5 que colocamos no ar nesse dia 27/09 resolve o problema?

Abraço e obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by paul0vinicius** [comment]
Olá, Fabricio.

Tudo certinho. Acabei de conferir as referências e agora parece estar tudo nos conformes.

Muito obrigado!

Atenciosamente,
